# Numpy

In [1]:
import numpy as np

In [3]:
a1 = np.array([1, 2, 3])
np.asarray([1, 2, 3])

array([1, 2, 3])

In [4]:
type(a1.tolist())

list

In [5]:
type(a1)

numpy.ndarray

In [10]:
ar = np.arange(0, 10, 2)
ar

array([0, 2, 4, 6, 8])

In [12]:
ar = np.linspace(1, 5, 10)
ar

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [32]:
a = np.random.randint(10, size=12).reshape(-1, 3).astype(np.float64)
a

array([[7., 9., 8.],
       [7., 2., 1.],
       [2., 5., 5.],
       [3., 0., 2.]])

In [ ]:
b = np.random.ranf()

In [26]:
a.astype(np.int64).sort()
a

array([0., 8., 1., 1., 9., 2., 7., 9., 4., 4.])

In [34]:
a

array([[7., 9., 8.],
       [7., 2., 1.],
       [2., 5., 5.],
       [3., 0., 2.]])

In [33]:
a.sum(axis=0)

array([19., 16., 16.])

In [35]:
a.sum(axis=1)

array([24., 10., 12.,  5.])

In [36]:
a.shape, a.size

((4, 3), 12)

In [37]:
t = np.array([True, False, False])
t.all(), t.any()

(np.False_, np.True_)

In [57]:
a[1:-1, 0:2]

array([[7., 2.],
       [2., 5.]])

In [ ]:
a[(a > 2) & (a < 8)] # | & ~

array([7., 7., 5., 5., 3.])

# Pandas

In [61]:
import pandas as pd