In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Day 1. Tensor Basics!

In [ ]:
a = torch.empty(1) # scalar value, value not initialized yet
a

tensor([-2.8021e+24])

In [5]:
a = torch.empty([2, 3])
a

tensor([[-1.3619e-11,  3.3906e-41,  0.0000e+00],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

In [15]:
a = torch.empty([3,])
a

tensor([-5.7604e-19,  3.3906e-41,  0.0000e+00])

In [16]:
b = torch.rand([2, 2])
b

tensor([[0.5007, 0.1833],
        [0.3618, 0.1794]])

In [18]:
b = torch.ones(2, 2)
b

tensor([[1., 1.],
        [1., 1.]])

In [22]:
c = torch.zeros([2, 3], dtype=torch.int)
c.dtype

torch.int32

In [29]:
arr = [2, 3, 1, 45]
a = torch.tensor(arr)
a

tensor([ 2,  3,  1, 45])

In [30]:
x = torch.rand([2, 2])
y = torch.rand([2, 2])
x, y

(tensor([[0.2318, 0.7052],
         [0.0594, 0.2370]]),
 tensor([[0.5762, 0.2044],
         [0.7939, 0.4198]]))

In [ ]:
x + y
torch.add(x, y)  # torch.add_(x, y)

x - y
torch.sub(x, y)  # torch.sub_(x, y)

x / y
torch.div(x, y)  # torch.div_(x, y)

x * y
torch.mul(x, y)  # torch.mul_(x, y)

tensor([[0.8080, 0.9097],
        [0.8533, 0.6567]])

In [32]:
x - y + y

tensor([[0.2318, 0.7052],
        [0.0594, 0.2370]])

In [33]:
x + y / 2

tensor([[0.5199, 0.8074],
        [0.4564, 0.4469]])

In [35]:
x[0]

tensor([0.2318, 0.7052])

In [37]:
torch.dot(x[0], y[0])

tensor(0.2777)

In [40]:
x.add(2)

tensor([[4.2318, 4.7052],
        [4.0594, 4.2370]])

In [39]:
x.add_(2) #inplace
x

tensor([[2.2318, 2.7052],
        [2.0594, 2.2370]])

In [42]:
x = torch.rand([5, 3])
x

tensor([[0.8963, 0.7810, 0.8243],
        [0.8946, 0.7171, 0.3172],
        [0.4631, 0.7369, 0.5892],
        [0.7482, 0.0369, 0.3502],
        [0.7531, 0.4460, 0.5883]])

In [44]:
x[1, :]

tensor([0.8946, 0.7171, 0.3172])

In [46]:
x[1, 1].item()

0.717079758644104

In [ ]:
# Reshaping

x = torch.rand([4, 4])
x

tensor([[0.9119, 0.7043, 0.9700, 0.1690],
        [0.6645, 0.0896, 0.1956, 0.5659],
        [0.0253, 0.2843, 0.8194, 0.0467],
        [0.9689, 0.4883, 0.2676, 0.0160]])

In [ ]:
x.view([8, -1])
# 8 by 2

tensor([[0.9119, 0.7043],
        [0.9700, 0.1690],
        [0.6645, 0.0896],
        [0.1956, 0.5659],
        [0.0253, 0.2843],
        [0.8194, 0.0467],
        [0.9689, 0.4883],
        [0.2676, 0.0160]])

In [ ]:
x.view([-1, 8])
# 2 by 8

tensor([[0.9119, 0.7043, 0.9700, 0.1690, 0.6645, 0.0896, 0.1956, 0.5659],
        [0.0253, 0.2843, 0.8194, 0.0467, 0.9689, 0.4883, 0.2676, 0.0160]])

In [53]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [ ]:
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
a

tensor([1., 1., 1., 1., 1.])

In [57]:
b = np.random.randint(2, 10, 10)
b

array([2, 7, 7, 4, 4, 6, 8, 4, 7, 9])

In [66]:
#b = torch.from_numpy(b)
b = b.to(torch.float16)

In [ ]:
b

# We can use tensors only on CPU, and if we moved tensor into GPU we can't come it back

tensor([2., 7., 7., 4., 4., 6., 8., 4., 7., 9.], dtype=torch.float16)

# Autograd. Calculating gradieents

In [69]:
x = torch.randn(3, requires_grad=True)
x

tensor([-1.0930, -1.9463, -0.3726], requires_grad=True)

In [70]:
y = x + 2
y

tensor([0.9070, 0.0537, 1.6274], grad_fn=<AddBackward0>)

In [71]:
z = y * y * 2
z

tensor([1.6453, 0.0058, 5.2969], grad_fn=<MulBackward0>)

In [72]:
z = z.mean()
z

tensor(2.3160, grad_fn=<MeanBackward0>)

In [73]:
z.backward() # dz / dx

In [74]:
x.grad

tensor([1.2093, 0.0715, 2.1699])

In [ ]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)
z = y * y * 2
# z = z.mean()
print(z)

# z.backward()
# print(x.grad)

tensor([ 1.1390, -0.9904, -1.6401], requires_grad=True)
tensor([3.1390, 1.0096, 0.3599], grad_fn=<AddBackward0>)
tensor(7.3349, grad_fn=<MeanBackward0>)


tensor(0.3734)